# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 17:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('url', models.URLField(null=True)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=16, null=True)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=16, null=True)),
                ('altitude', models.DecimalField(decimal_places=10, max_digits=16, null=True)),
                ('publication_creation', models.DateTimeField()),
                ('publication_begin', models.DateTimeField()),
                ('publication_end', models.DateTimeField(null=True)),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
