# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='altitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=16, null=True),
        ),
    ]
