# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160809_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
