# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20160831_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='preview',
            field=models.BooleanField(default=False),
        ),
    ]
