# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 14:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_image_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='begin_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
