# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20160831_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='begin_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
